services:
  - type: web
    name: alphax-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
    # Environment variables to be set in Render dashboard:
    # - OPENROUTER_API_KEY (your actual API key)
    # - SECRET_KEY (generate a secure random key)
    # - SITE_URL (will be your render app URL)
    # - APP_NAME (AlphaX)